# Generated by Django 4.2.3 on 2023-09-21 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_maquina', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('statu', models.CharField(choices=[('Q', 'Quebrada'), ('P', 'Preventiva'), ('C', 'Corretiva'), ('O', 'OUTROS')], max_length=1)),
                ('data_do_defeito', models.DateTimeField()),
                ('chamado', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=150)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='desafio.usuario')),
            ],
        ),
    ]
