# Generated by Django 4.2.3 on 2023-09-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
