# Generated by Django 4.2.3 on 2023-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_rename_cpf_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='CPF',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
