# Generated by Django 4.2.3 on 2023-10-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0002_funcionario_alter_usuario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_obra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
