# Generated by Django 4.2.3 on 2023-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0004_logistica_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
