# Generated by Django 4.2.3 on 2023-10-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0006_manuntencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_automovel',
            name='ano',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
