# Generated by Django 4.2.3 on 2023-10-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0007_alter_categoria_automovel_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_automovel',
            name='ano',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='categoria_servico',
            name='valor_obra',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nif',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='patrimonio',
            field=models.DecimalField(decimal_places=0, max_digits=120),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='valor_compra',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='valor_venda',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
