# Generated by Django 4.2.3 on 2023-10-04 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0008_alter_categoria_automovel_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='posto_trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=1)),
                ('funcionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarioo', to='mange_automotive.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='manuntencao',
            name='mao_obra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.DateField()),
                ('funcionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='mange_automotive.funcionario')),
                ('nome_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='mange_automotive.usuario')),
                ('posto_trabalho_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posto_trabalho', to='mange_automotive.posto_trabalho')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=0, max_digits=5)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('B', 'BOLETO'), ('CC', 'CARTAO DE CREDITO'), ('CD', 'DEBITO')], max_length=100)),
                ('dados', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=5)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], max_length=100)),
                ('manuntencao_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuntencao', to='mange_automotive.manuntencao')),
            ],
        ),
    ]
