# Generated by Django 4.2.3 on 2023-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0012_alter_manuntencao_servico_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_servico',
            name='valor_obra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='logistica_loja',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
