# Generated by Django 4.2.3 on 2023-10-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0015_alter_manuntencao_servico_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuntencao',
            name='logistica_fk',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mange_automotive.logistica_loja'),
        ),
    ]
