# Generated by Django 4.2.3 on 2023-10-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0016_alter_manuntencao_logistica_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuntencao',
            name='logistica_fk',
        ),
        migrations.AddField(
            model_name='manuntencao',
            name='logistica_fk',
            field=models.ManyToManyField(blank=True, default=None, to='mange_automotive.logistica_loja'),
        ),
    ]
