# Generated by Django 4.2.3 on 2023-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0019_remove_manuntencao_mao_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuntencao',
            name='mao_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
