# Generated by Django 4.2.3 on 2023-10-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0020_manuntencao_mao_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuntencao',
            name='logistica_fk',
            field=models.ManyToManyField(to='mange_automotive.logistica_loja'),
        ),
        migrations.AlterField(
            model_name='manuntencao',
            name='servico_fk',
            field=models.ManyToManyField(to='mange_automotive.categoria_servico'),
        ),
    ]
