# Generated by Django 4.2.3 on 2023-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0021_alter_manuntencao_logistica_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuntencao',
            name='mao_obra',
        ),
        migrations.AlterField(
            model_name='manuntencao',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
