# Generated by Django 4.2.3 on 2023-10-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0022_remove_manuntencao_mao_obra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuntencao',
            old_name='sub_total',
            new_name='mao_obra',
        ),
    ]
