# Generated by Django 4.2.3 on 2023-10-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0026_alter_pagamento_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='funcionario_fk',
        ),
    ]
