# Generated by Django 4.2.7 on 2023-11-28 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230528_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 22, 26, 14, 997004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 22, 26, 14, 997004, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
