# Generated by Django 4.2.3 on 2023-09-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('CPF', models.IntegerField()),
                ('email', models.CharField(max_length=150, null=True)),
                ('cep', models.IntegerField()),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
