# Generated by Django 4.2.3 on 2023-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.CharField(max_length=150, null=True)),
                ('descrição', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
                ('endereço', models.IntegerField()),
                ('cidade', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('Q', 'Quebrada'), ('P', 'Preventiva'), ('C', 'Corretiva'), ('O', 'OUTROS')], max_length=1)),
            ],
        ),
    ]
