# Generated by Django 4.2.3 on 2023-09-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_viagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagens',
            name='categoria',
            field=models.CharField(choices=[('P', 'PRAIA'), ('C', 'CAMPO ABERTO'), ('C', 'CIDADE'), ('M', 'MEDIEVAL'), ('C', 'CASA')], max_length=1),
        ),
    ]
