# Generated by Django 4.2.3 on 2023-09-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_alter_viagens_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagem', models.CharField(max_length=150, null=True)),
                ('descrição', models.CharField(max_length=150)),
                ('valor', models.IntegerField()),
                ('endereço', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('P', 'PRAIA'), ('C', 'CAMPO ABERTO'), ('C', 'CIDADE'), ('M', 'MEDIEVAL'), ('C', 'CASA')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='viagens',
        ),
    ]
