# Generated by Django 4.2.3 on 2023-09-26 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_viagem_delete_viagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viagem',
            new_name='viagens',
        ),
    ]
