# Generated by Django 4.2.3 on 2023-09-27 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_categoria_alter_viagens_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_viagem_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_inicio', models.DateTimeField()),
                ('data_do_fim', models.DateTimeField()),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro', to='desafio.cadastro')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='desafio.viagens')),
            ],
        ),
    ]
