# Generated by Django 4.2.3 on 2023-09-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0007_cadastro_viagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_viagem_usuario',
            name='data_do_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cadastro_viagem_usuario',
            name='data_do_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='descrição',
            field=models.TextField(),
        ),
    ]
