# Generated by Django 4.2.3 on 2023-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0008_alter_cadastro_viagem_usuario_data_do_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_viagem_usuario',
            name='cadastro',
        ),
    ]
