# Generated by Django 4.2.3 on 2023-10-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0009_remove_cadastro_viagem_usuario_cadastro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_viagem_usuario',
            new_name='cadastro_viagem_data',
        ),
    ]
