# Generated by Django 4.2.3 on 2023-10-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0010_rename_cadastro_viagem_usuario_cadastro_viagem_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_viagem_data',
            new_name='cadastro_viagem',
        ),
    ]
