# Generated by Django 4.2.3 on 2023-10-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0011_rename_cadastro_viagem_data_cadastro_viagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_viagem',
            new_name='cadastro_viagems',
        ),
        migrations.RenameField(
            model_name='cadastro_viagems',
            old_name='viagem',
            new_name='viagens',
        ),
    ]
