# Generated by Django 4.2.3 on 2023-10-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0012_rename_cadastro_viagem_cadastro_viagems_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_viagems',
            new_name='cadastro_viagem',
        ),
    ]
