# Generated by Django 4.2.3 on 2023-10-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0013_rename_cadastro_viagems_cadastro_viagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cadastro_viagem',
        ),
    ]
