# Generated by Django 4.2.3 on 2023-10-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0014_delete_cadastro_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='desafio.viagens')),
            ],
        ),
    ]
