# Generated by Django 4.2.3 on 2023-10-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0015_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='data_fim',
        ),
    ]
