# Generated by Django 4.2.3 on 2023-10-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0016_remove_horario_data_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='data_inicio',
        ),
    ]
