# Generated by Django 4.2.3 on 2023-10-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0017_remove_horario_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='viagem',
        ),
        migrations.AddField(
            model_name='horario',
            name='deus',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
