# Generated by Django 4.2.3 on 2023-10-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0019_alter_horario_deus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='deus',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
