# Generated by Django 4.2.3 on 2023-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0020_alter_horario_deus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='deus',
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_inicio',
            field=models.DateField(null=True),
        ),
    ]
