# Generated by Django 4.2.3 on 2023-10-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0021_remove_horario_deus_horario_horario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
