# Generated by Django 4.2.3 on 2023-10-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0022_alter_horario_horario_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='horario_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='desafio.viagens'),
        ),
    ]
