# Generated by Django 4.2.3 on 2023-10-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0023_horario_horario_fim_horario_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='desafio.viagens'),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='desafio.categoria'),
        ),
    ]
