# Generated by Django 4.2.3 on 2023-10-01 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0024_alter_horario_horario_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Recusado')], max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.categoriapagamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafio.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='desafio.pagamento')),
            ],
        ),
    ]
