# Generated by Django 4.2.3 on 2023-10-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0025_categoriapagamento_pagamento_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pagamento',
        ),
        migrations.DeleteModel(
            name='CategoriaPagamento',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
