# Generated by Django 4.2.3 on 2023-10-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0026_remove_pagamento_categoria_remove_pagamento_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pagamento', models.CharField(choices=[('P', 'PIX'), ('D', 'DEBITO'), ('C', 'CREDITO'), ('B', 'BOLETO')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'APROVADO'), ('R', 'RECUSADO')], max_length=1)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastro', to='desafio.cadastro')),
            ],
        ),
    ]
