# Generated by Django 4.2.3 on 2023-10-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0027_horario_valor_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='registrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='desafio.horario'),
        ),
    ]
