# Generated by Django 4.2.3 on 2023-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0029_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
