# Generated by Django 4.2.3 on 2023-10-07 19:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mange_automotive', '0009_posto_trabalho_manuntencao_mao_obra_reserva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('purchaseValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('people', models.IntegerField()),
                ('hasPet', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], default='P', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('taxId', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('PIX', 'PIX'), ('BS', 'BANK SLIP'), ('CC', 'CREDIT CARD'), ('CD', 'DEBT CARD')], max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], default='P', max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('bookingFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingPayment', to='mange_automotive.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('daily', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('categoryFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryTrip', to='mange_automotive.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='manuntencao',
            name='automovel_fk',
        ),
        migrations.RemoveField(
            model_name='manuntencao',
            name='funcionario_fk',
        ),
        migrations.RemoveField(
            model_name='manuntencao',
            name='logistica_fk',
        ),
        migrations.RemoveField(
            model_name='manuntencao',
            name='servico_fk',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='manuntencao_fk',
        ),
        migrations.RemoveField(
            model_name='posto_trabalho',
            name='funcionario_fk',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='funcionario_fk',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nome_fk',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='posto_trabalho_fk',
        ),
        migrations.DeleteModel(
            name='categoria_automovel',
        ),
        migrations.DeleteModel(
            name='categoria_servico',
        ),
        migrations.DeleteModel(
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='logistica_loja',
        ),
        migrations.DeleteModel(
            name='manuntencao',
        ),
        migrations.DeleteModel(
            name='pagamento',
        ),
        migrations.DeleteModel(
            name='posto_trabalho',
        ),
        migrations.DeleteModel(
            name='reserva',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='image',
            name='tripFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripImage', to='mange_automotive.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customUserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserBooking', to='mange_automotive.customuser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tripFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='mange_automotive.trip'),
        ),
        migrations.AddField(
            model_name='availability',
            name='bookingFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingAvailability', to='mange_automotive.booking'),
        ),
        migrations.AddField(
            model_name='availability',
            name='tripFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripAvailability', to='mange_automotive.trip'),
        ),
    ]
