# Generated by Django 4.2.3 on 2023-10-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0010_availability_booking_category_customuser_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='categoria_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_obra', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nif', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='logistica_loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('patrimonio', models.DecimalField(decimal_places=0, max_digits=120)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10)),
                ('valor_compra', models.DecimalField(decimal_places=0, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='manuntencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mao_obra', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('automovel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_automovel', to='mange_automotive.categoria_automovel')),
                ('funcionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='mange_automotive.funcionario')),
                ('logistica_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistica_loja', to='mange_automotive.logistica_loja')),
                ('servico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_servico', to='mange_automotive.categoria_servico')),
            ],
        ),
        migrations.CreateModel(
            name='pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=0, max_digits=5)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('B', 'BOLETO'), ('CC', 'CARTAO DE CREDITO'), ('CD', 'DEBITO')], max_length=100)),
                ('dados', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=0, max_digits=5)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Cancelado(a)'), ('A', 'Aprovado(a)')], max_length=100)),
                ('manuntencao_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuntencao', to='mange_automotive.manuntencao')),
            ],
        ),
        migrations.CreateModel(
            name='posto_trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=1)),
                ('funcionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarioo', to='mange_automotive.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.DateField()),
                ('funcionario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='mange_automotive.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.DecimalField(decimal_places=0, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customUserFK',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tripFK',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tripFk',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bookingFK',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='categoryFK',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='mange_automotive.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='posto_trabalho_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posto_trabalho', to='mange_automotive.posto_trabalho'),
        ),
    ]
