# Generated by Django 4.2.3 on 2023-10-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0011_categoria_automovel_categoria_servico_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuntencao',
            name='servico_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_servico', to='mange_automotive.categoria_servico'),
        ),
    ]
