# Generated by Django 4.2.3 on 2023-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0025_remove_manuntencao_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
