# Generated by Django 4.2.3 on 2023-10-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0028_remove_usuario_email_alter_reserva_nome_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm', to='mange_automotive.usuario'),
        ),
    ]
