# Generated by Django 4.2.3 on 2023-10-14 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mange_automotive', '0029_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_automovel',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='mange_automotive.usuario'),
        ),
    ]
